# Generated by Django 5.1.2 on 2024-10-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='ast_json',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='rule_name',
        ),
        migrations.AddField(
            model_name='rule',
            name='ast_representation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_string',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ASTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_child', to='rule_app.astnode')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_child', to='rule_app.astnode')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='root_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='rule_app.astnode'),
        ),
    ]
